##  numpy
### basically numpy gives access to 'numpy array' 
### all elements within numpy array are of same type 
### contiguous allocation of elements in a memory 
### contiguous means elements reside side by side in a memory
### user can directly access the elements with a[2][3] like notation 
### far efficient than python lists

### importing numpy

In [3]:
import numpy as np

### creating numpy arrays


In [5]:
a = np.array([1,2,3])
b = np.array([3,4,5])

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([3, 4, 5])

### checking type

In [11]:
a.dtype

dtype('int32')

### creating numpy array of specific data type

In [15]:
a = np.array([1,2,3], dtype = 'int8')


In [16]:
a

array([1, 2, 3], dtype=int8)

In [17]:
a.dtype

dtype('int8')

In [19]:
a.itemsize # size of each item in an array

1

In [23]:
a.nbytes  # itemsize * num of items in an array 

3

## accessing elements

In [25]:
a[0]

1

In [26]:
a[1]

2

In [27]:
a[2]

3

In [29]:
a[3] # will generate index error

IndexError: index 3 is out of bounds for axis 0 with size 3

### checking dimension and shape

In [33]:
a.shape # return a tuple, showing number of elements

(3,)

In [34]:
a.ndim # return dimension of an array

1

In [35]:
b = np.array([[1,2,3],[3,4,5]])

In [36]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [37]:
b.ndim

2

In [38]:
b.shape

(2, 3)

In [39]:
b.shape[0] # returns a number of rows

2

In [41]:
b.shape[1] # returns a number of columns

3

In [42]:
a = np.array([[x for x in range(1, 8)], [x for x in range(8, 15)]])

In [43]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [44]:
a[1,1] # picking a number 9

9

In [45]:
a[0] # returns first row

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
a[:, 1]  # selcting first column

array([2, 9])

In [48]:
a[:, 2:4] # selecting all rows, selecting columns 2,3

array([[ 3,  4],
       [10, 11]])

In [49]:
a[1, 5:] #slicing just gives a view, it doesnot create separate copy

array([13, 14])

In [50]:
a[0, 2::2]

array([3, 5, 7])

In [53]:
a[0, 2::2] = [13, 14,15]

In [54]:
a

array([[ 1,  2, 13,  4, 14,  6, 15],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [56]:
 b = np.array([[[x for x in range(1,4)],[x for x in range(1,4)]],[[x for x in range(1,4)],[x for x in range(1,4)]]])

In [57]:
b

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [58]:
b[0, 0, 0]

1

In [61]:
b[0,:,0:2] = [[3,4],[5,6]]

In [62]:
b

array([[[3, 4, 3],
        [5, 6, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [64]:
c = np.zeros(5)

In [65]:
c.dtype

dtype('float64')

In [66]:
c = np.zeros((3,3))

In [67]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
c.ndim

2

In [69]:
c.shape

(3, 3)

In [71]:
c = np.full((2,2), 2)

In [72]:
c.dtype

dtype('int32')

In [73]:
c = np.full((3,3), 1, dtype='int8')

In [74]:
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [75]:
c.itemsize

1

In [76]:
c.nbytes

9

In [77]:
d = np.full(c.shape, 5)

In [78]:
d

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [79]:
d.nbytes

36

In [80]:
d.itemsize

4

In [81]:
## random decimal numbers

In [83]:
x  = np.random.rand(3,3)  #got values uniformally distributed

In [84]:
x

array([[0.04296569, 0.63930619, 0.47327274],
       [0.02520253, 0.37795181, 0.2685509 ],
       [0.65929711, 0.38190818, 0.79045546]])

In [90]:
y = np.random.randint(1,101,size=(3,3))

array([[ 58,  38,  73],
       [ 29,  75,   9],
       [ 58, 100,  49]])

In [91]:
num = np.random.randint(1, 100)

In [92]:
num

66

In [97]:
arr = np.array([[1,2,3]])

In [102]:
r1 = np.repeat(arr, 3, axis = 1)

In [103]:
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [104]:
output = np.ones((5,5))

In [105]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [107]:
part = np.zeros((3,3))

In [108]:
part

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [109]:
part[1,1] = 9

In [110]:
output[1:4, 1:4] = part

In [111]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
a = np.array([1,2,3])

In [113]:
b = a

In [114]:
b

array([1, 2, 3])

In [115]:
a

array([1, 2, 3])

In [119]:
a[0] = 90

In [120]:
a

array([90,  2,  3])

In [121]:
b

array([90,  2,  3])

In [122]:
c = a.copy()

In [123]:
c

array([90,  2,  3])

In [124]:
## mathematics

In [125]:
a = np.array([1,2,3,4])

In [126]:
a

array([1, 2, 3, 4])

In [127]:
a + 2

array([3, 4, 5, 6])

In [128]:
a - 2 

array([-1,  0,  1,  2])

In [129]:
a * 2

array([2, 4, 6, 8])

In [130]:
a = a * 2

In [131]:
a

array([2, 4, 6, 8])

In [132]:
a = a / 2

In [133]:
a

array([1., 2., 3., 4.])

## magic of vector processing

In [134]:
a = np.array([1,2,3])

In [135]:
a

array([1, 2, 3])

In [136]:
a + 2

array([3, 4, 5])

In [137]:
a - 2

array([-1,  0,  1])

In [138]:
a * 2

array([2, 4, 6])

In [139]:
a = a * 2

In [140]:
a

array([2, 4, 6])

In [141]:
a / 2

array([1., 2., 3.])

In [144]:

a.dtype

dtype('int32')

In [145]:
a = np.array([1,2,3])

In [146]:
b = np.array([3,4,5])

In [147]:
a + b

array([4, 6, 8])

In [148]:
b - a

array([2, 2, 2])

In [149]:
a * b

array([ 3,  8, 15])

In [150]:
a / b

array([0.33333333, 0.5       , 0.6       ])

In [151]:
for item in a/b:
    print(item)

0.3333333333333333
0.5
0.6


In [152]:
a ** b

array([  1,  16, 243], dtype=int32)

In [153]:
a

array([1, 2, 3])

In [154]:
b

array([3, 4, 5])

In [157]:
## linera algebra

In [158]:
a = np.full((2,3), 1)

In [159]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [160]:
b = np.full((3,2), 2)

In [161]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [162]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [163]:
np.linalg.det(np.matmul(a,b))

0.0

In [164]:
a = np.array([1,2,3,4,5,6])

In [165]:
np.min(a)

1

In [166]:
np.max(a)

6

In [167]:
np.mean(a)

3.5

In [168]:
np.sum(a)

21

In [169]:
np.sum(a) / np.size(a)

3.5

In [170]:
np.size(a)

6

In [171]:
a = np.array([[x for x in range(1,4)],[x for x in range(1,4)]])

In [172]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [173]:
np.min(a, axis = 0)

array([1, 2, 3])

In [174]:
np.min(a, axis = 1)

array([1, 1])

In [175]:
np.max(a, axis = 0)

array([1, 2, 3])

In [177]:
np.max(a, axis = 1)

array([3, 3])

In [179]:
np.mean(a, axis = 0).dtype


dtype('float64')

In [180]:
np.mean(a, axis = 1)

array([2., 2.])

In [181]:
np.sum(a, axis = 0)

array([2, 4, 6])

In [182]:
np.sum(a, axis = 1)

array([6, 6])

In [183]:
before = np.array([[x for x in range(1,5)], [x for x in range(5,9)]])

In [184]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [185]:
before.shape

(2, 4)

In [188]:
after = before.reshape(1, 8)

In [189]:
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [190]:
after.ndim

2

In [191]:
after.shape

(1, 8)

In [192]:
after.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [193]:
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [195]:

after[0][2] = 999

In [196]:
after

array([[  1,   2, 999,   4,   5,   6,   7,   8]])

In [197]:
after = after.reshape(2,4)

In [198]:
after

array([[  1,   2, 999,   4],
       [  5,   6,   7,   8]])

In [201]:
v1 = np.array([x for x in range(5)])
v2 = np.array([x for x in range(5)])

In [203]:
v1
v2

array([0, 1, 2, 3, 4])

In [207]:
np.vstack([v1,v2]).shape

(2, 5)

In [209]:
np.hstack([v1,v2]).ndim

1

In [210]:
## load data from file

In [212]:
file = open('a.txt', mode = 'w')

In [214]:
for i in range(1,11):
    file.write(str(i))

In [215]:
file.close()

In [216]:
file = open('a.txt', mode = 'r')

In [217]:
txt = file.read()

In [218]:
txt

'12345678910'

In [219]:
file = open('a.txt', mode = 'w')

In [220]:
for i in range(1, 11):
    file.write(f'{i} ')

In [221]:
file.close()

In [224]:
file = open('a.txt', mode = 'r')

In [225]:
txt =  file.read()

In [226]:
txt

'1 2 3 4 5 6 7 8 9 10 '

In [227]:
file.close()

In [236]:
a = np.genfromtxt('a.txt', delimiter=' ')

In [237]:
np.size(a)

10

In [239]:
for i in range(np.size(a)):
    print(a[i])

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [240]:
a.reshape(5,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [241]:
##masking and advance indexing

In [242]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [243]:
a[ a > 5]

array([ 6.,  7.,  8.,  9., 10.])

In [244]:
a[[0,2,4]]

array([1., 3., 5.])

In [245]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [247]:
a = np.array([[x for x in range(1,4)],[x for x in range(2,5)]])

In [248]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [249]:
a[a > 2]

array([3, 3, 4])

In [250]:
a[a > 2, axis = 0] 

SyntaxError: invalid syntax (<ipython-input-250-969aa5a66c65>, line 1)

In [251]:
np.any(a > 2, axis = 0)

array([False,  True,  True])

In [253]:
np.all(a > 2, axis = 1)

array([False, False])

In [257]:
a[(a > 2) & (a < 5)]

array([3, 3, 4])